"""TPVFuser: extract fused 3D voxel features from 3 TPV planes.

Adapted from PointOcc TPVAggregator_Occ — keeps only the grid_sample fusion
(no decoder, no classifier, no loss).  Output is a dense 3D tensor that the
caller can collapse along Z for BEV-level fusion.

Inputs
------
tpv_list : list of 3 tensors  [tpv_xy, tpv_yz, tpv_zx]
    tpv_xy: (B, C, W, H)
    tpv_yz: (B, C, H, Z)
    tpv_zx: (B, C, Z, W)

voxels_coarse : (B, N, 3)
    Continuous cylindrical grid coordinates for every coarse Cartesian
    voxel centre.  Generated by the data pipeline (cart2polar + normalise).

Output
------
fused : (B, C, W_occ, H_occ, D_occ)
    Dense 3D feature volume at coarse occupancy resolution.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from mmcv.runner import BaseModule
from mmdet3d.models.builder import FUSION_LAYERS


@FUSION_LAYERS.register_module()
class TPVFuser(BaseModule):
    """Grid-sample fusion of 3 TPV planes into a dense 3D volume."""

    def __init__(self,
                 tpv_h, tpv_w, tpv_z,
                 grid_size_occ,
                 coarse_ratio=1,
                 scale_h=2, scale_w=2, scale_z=2,
                 use_checkpoint=False):
        super().__init__()
        self.tpv_h = tpv_h
        self.tpv_w = tpv_w
        self.tpv_z = tpv_z
        self.scale_h = scale_h
        self.scale_w = scale_w
        self.scale_z = scale_z
        self.grid_size_occ = np.asarray(grid_size_occ).astype(np.int32)
        self.coarse_ratio = coarse_ratio
        self.use_checkpoint = use_checkpoint

    def forward(self, tpv_list, voxels_coarse):
        """
        Args:
            tpv_list: list of 3 TPV plane tensors
            voxels_coarse: (B, N, 3) continuous cylindrical grid coords

        Returns:
            fused: (B, C, W_coarse, H_coarse, D_coarse) dense 3D feature
        """
        tpv_xy, tpv_yz, tpv_zx = tpv_list[0], tpv_list[1], tpv_list[2]
        # Permute to [B, C, H, W] / [B, C, Z, H] / [B, C, W, Z]
        tpv_hw = tpv_xy.permute(0, 1, 3, 2)
        tpv_wz = tpv_zx.permute(0, 1, 3, 2)
        tpv_zh = tpv_yz.permute(0, 1, 3, 2)
        bs, c, _, _ = tpv_hw.shape

        # Interpolate TPV planes to target resolution
        if self.scale_h != 1 or self.scale_w != 1:
            tpv_hw = F.interpolate(
                tpv_hw,
                size=(int(self.tpv_h * self.scale_h),
                      int(self.tpv_w * self.scale_w)),
                mode='bilinear', align_corners=False)
        if self.scale_z != 1 or self.scale_h != 1:
            tpv_zh = F.interpolate(
                tpv_zh,
                size=(int(self.tpv_z * self.scale_z),
                      int(self.tpv_h * self.scale_h)),
                mode='bilinear', align_corners=False)
        if self.scale_w != 1 or self.scale_z != 1:
            tpv_wz = F.interpolate(
                tpv_wz,
                size=(int(self.tpv_w * self.scale_w),
                      int(self.tpv_z * self.scale_z)),
                mode='bilinear', align_corners=False)

        # Normalise voxel coordinates to [-1, 1] for grid_sample
        _, n, _ = voxels_coarse.shape
        voxels_coarse = voxels_coarse.reshape(bs, 1, n, 3).clone()
        voxels_coarse[..., 0] = voxels_coarse[..., 0] / (
            self.tpv_w * self.scale_w) * 2 - 1
        voxels_coarse[..., 1] = voxels_coarse[..., 1] / (
            self.tpv_h * self.scale_h) * 2 - 1
        voxels_coarse[..., 2] = voxels_coarse[..., 2] / (
            self.tpv_z * self.scale_z) * 2 - 1

        # Sample from each TPV plane at coarse voxel locations
        sample_xy = voxels_coarse[:, :, :, [0, 1]]
        tpv_hw_vox = F.grid_sample(
            tpv_hw, sample_xy, padding_mode="border",
            align_corners=False).squeeze(2)  # (B, C, N)

        sample_yz = voxels_coarse[:, :, :, [1, 2]]
        tpv_zh_vox = F.grid_sample(
            tpv_zh, sample_yz, padding_mode="border",
            align_corners=False).squeeze(2)

        sample_zx = voxels_coarse[:, :, :, [2, 0]]
        tpv_wz_vox = F.grid_sample(
            tpv_wz, sample_zx, padding_mode="border",
            align_corners=False).squeeze(2)

        # Fuse: element-wise sum of 3 plane features
        fused = tpv_hw_vox + tpv_zh_vox + tpv_wz_vox  # (B, C, N)

        # Reshape to dense 3D volume
        W = int(self.grid_size_occ[0] / self.coarse_ratio)
        H = int(self.grid_size_occ[1] / self.coarse_ratio)
        D = int(self.grid_size_occ[2] / self.coarse_ratio)
        fused = fused.reshape(bs, c, W, H, D)  # (B, C, W, H, D)

        return fused
